apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: opswatch
  labels:
    app.kubernetes.io/name: opswatch
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: coderhouse
  POSTGRES_DB: opswatch
  DATABASE_URL: postgresql://postgres:coderhouse@postgres:5432/opswatch
